config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe/webhooks'

  get 'pages/home'
  get 'pages/admin'
  get 'pages/tees'
  get 'pages/hats'
  get 'pages/jackets'
  get 'pages/accessories'
  get 'pages/subscription'
  get 'pages/about'
  get 'pages/register'

  get 'seller' => "posts#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'checking' => "brands#checking"
  get 'register' => "pages#register"
  get 'artists' => "brands#index"

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks =>"omniauth_callbacks"}


  #root "pages#home"
  #root 'pages#home'
  root 'exhibitions#index'

  resources :posts do
  	put :favorite, on: :member
  	put :like, on: :member

    resources :orders, only: [:new, :create] 

  end

  resources :profiles

  resource :subscription
  resource :card
  resources :addresses

  resources :credits 

  resources :brands


  resources :exhibitions do
      resources :posts
  
  end

  

end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
	belongs_to :user
	has_many :posts

	has_attached_file :image, :styles => { :large => "1600x800#", :medium => "800x400#", :thumb => "400x200#" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
	before_action :find_exhibition, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

def index
	@brands = Brand.active
	@exhibitions = Exhibition.all.order("created_at DESC")
end

def show
		if user_signed_in?
	      @favorites = current_user.favorites
	      @likes = current_user.likes
	    end
	@brands = Brand.active
	@posts = @exhibition.posts
end

def new
	@brands = Brand.active
	@exhibition = current_user.exhibitions.build
end

def create
	@exhibition = current_user.exhibitions.build(exhibition_params)

	if @exhibition.save
		redirect_to @exhibition
	else
		render 'new'
	end
end

def edit
	@brands = Brand.active
end

def update
	if @exhibition.update(exhibition_params)
		redirect_to @exhibition
	else
		render 'edit'
	end
end

def destroy
	@exhibition.destroy
	redirect_to root_path
end

private

	def find_exhibition
		@exhibition = Exhibition.find(params[:id])
	end

	def exhibition_params
		params.require(:exhibition).permit(:title, :description, :image)
	end

end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_exhibition.html.erb
<li class="exhibitionlist">
	<%= link_to exhibition_path(exhibition) do %>
		<div class="exhibitioncontent">
			<h1><%= exhibition.title %></h1>
			<p><%= exhibition.description %></p>
		</div>

	<% end %>

	<%= image_tag exhibition.image.url(:large), class: "exhibitionimage" %>

</li>

app/views/exhibitions/_form.html.erb
<div class="panel-body">
  <div class="panel panel-default">

	<%= simple_form_for(@exhibition, html: { multiport: true }) do |f| %>

	      <%= f.error_notification %>

	  <%= f.input :title, label: "Title" %>
	  <%= f.input :description, label: "Tell us more" %>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control" %>
      </div>

	  <%= f.button :submit, "Submit", class: "button" %>

	<% end %>
	</div>
</div>

app/views/exhibitions/edit.html.erb
<% if can? :manage, :all %>
<div class="signup-back">
  <div class="panel-heading">
    <h1>Edit Exhibition</h1>
  </div>


	<%= render 'form' %>

	<%= link_to 'Back', exhibitions_path %>
</div>
<% end %>

app/views/exhibitions/index.html.erb
<div class="postsection">

	<% if @exhibitions.any? %>

		<ul>
			<%= render @exhibitions %>
		</ul>

	<% end %>

	<%= link_to "View All Artwork", posts_path, class: "allposts" %>
</div>

app/views/exhibitions/new.html.erb
<% if can? :manage, :all %>
<div class="signup-back">
  <div class="panel-heading">
    <h1>Add Exhibition</h1>
  </div>



	<%= render 'form' %>

	<%= link_to 'Back', exhibitions_path %>
</div>
<% end %>

app/views/exhibitions/show.html.erb
<div class="exhibitionlist">

		<div class="exhibitioncontent">
			<h1><%= @exhibition.title %></h1>
			<p><%= @exhibition.description %></p>
		</div>


	<%= image_tag @exhibition.image.url(:large), class: "exhibitionimage" %>

</div>

<div class="postsection">
	<% if @posts.any? %>

	<ul>
		<%= render @posts %>
	</ul>

	<% end %>
</div>