config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe/webhooks'

  get 'pages/home'
  get 'pages/admin'
  get 'pages/tees'
  get 'pages/hats'
  get 'pages/jackets'
  get 'pages/accessories'
  get 'pages/subscription'
  get 'pages/about'
  get 'pages/register'

  get 'seller' => "posts#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'checking' => "brands#checking"
  get 'register' => "pages#register"
  get 'artists' => "brands#index"

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks =>"omniauth_callbacks"}


  #root "pages#home"
  #root 'pages#home'
  root 'exhibitions#index'

  resources :posts do
  	put :favorite, on: :member
  	put :like, on: :member

    resources :orders, only: [:new, :create] 

  end

  resources :profiles

  resource :subscription
  resource :card
  resources :addresses

  resources :credits 

  resources :brands


  resources :exhibitions do
      resources :posts
  
  end

  

end

app/views/pages/about.html.erb
<div class="homesection">
	<div class="aboutimage">



		<div class="aboutinformation">

			<h1>ZOE</h1>


			<p>Zoe is your art dealer.  Zoe is the first exhibition focused online gallery.  Zoe partners with talented artists to showcase their exhibitions and original artwork.  Our goal is to provide an easy to use website and excellent customer service for our customers.</p>


		</div>

	</div>




</div>

app/views/pages/accessories.html.erb
<div class="postsection">
<% if @posts.any? %>

<ul>
	<%= render @posts %>
</ul>

<% end %>
</div>

app/views/pages/admin.html.erb
<% if can? :manage, :all %>
<div class="postsection">
<% if @posts.any? %>

<ul>
	<% @posts.each do |post| %>
<li>
	<div class="postbox <%= post.id %>">

		<div class="imagecircle <%= post.id %>">
		<div class="postinfo nodisplay <%= post.id %>">
			<h1><%= post.brand %></h1>
			<h2><%= post.title %></h2>


		</div>
			<%= image_tag post.image.url(:medium) %>




		</div>



		<div class="postbuttons <%= post.id %>">

		<% if post.link.present? %>

		<%= link_to post.link, :target => "_blank" do %>
			<div class="allbutton linkbutton <%= post.id %>">
				<i class="fa fa-usd"></i>
				<p>BUY / <%= post.price %></p>

			</div>
		<% end %>

		<% else %>
			<div class="allbutton linkbutton <%= post.id %>">
				<i class="fa fa-usd"></i>
				<p>COMING SOON / <%= post.price %></p>

			</div>

		<% end %>


			<div class="allbutton likebutton <%= post.id %>">
				<i class="fa fa-heart"></i>
				<p>SHARE / <span class="likeup <%= post.id %>"><%= post.liked_by.count %></span></p>

			</div>


			<div class="allbutton savebutton <%= post.id %>">
				<i class="fa fa-exclamation"></i>
				<p>CAP / <span class="favup <%= post.id %>"><%= post.favorited_by.count %></span></p>

			</div>


					

		</div>

		<div>
			<%= link_to 'Edit', edit_post_path(post) %>
         	<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
         	<%= post.impressionist_count(:filter=>:session_hash) %>

		</div>

	</div>
</li>

<script>

  $('.imagecircle' + '.<%= post.id %>').mouseover(function(){
    $('.postinfo' + '.<%= post.id %>').removeClass("nodisplay");
  });
  $('.imagecircle' + '.<%= post.id %>').mouseleave(function(){
    $('.postinfo' + '.<%= post.id %>').addClass("nodisplay");
  });
</script>



	<% end %>
</ul>

<% end %>
</div>

<% end %>

app/views/pages/hats.html.erb
<div class="postsection">
	<% if user_signed_in? %>
	<% if current_user.credits.where(creditactive: true).count > 1 %>
	<div class="creditalert">
		You have <%= current_user.credits.where(creditactive: true).count %> credits available to use.  Just hit "Use Credit" when placing order.
	</div>

	<% elsif current_user.credits.where(creditactive: true).count > 0 %>
	<div class="creditalert">
		You have <%= current_user.credits.where(creditactive: true).count %> credit available to use.  Just hit "Use Credit" when placing order.
	</div>
	<% end %>
	<% end %>
<% if @posts.any? %>

<ul>
	<%= render @posts %>
</ul>

<% end %>
</div>

app/views/pages/home.html.erb
<div class="homesection">
	<div class="homeimage">
		<%= link_to pages_hats_path do %>

		<%= image_tag 'plughatimage.png', :class => "fullimage" %>

		<% end %>

	</div>

	<div class="homeinfobox">
		<div class="homeinfo1">
			<p>Each week we design random "sometimes cool" hats.  You choose
				which one you want for the month.  Delivered by black doves to your
				doorstep (much faster than a drone).</p>
		</div>

		<%= link_to pages_subscription_path do %>
		<div class="homesignupbox">
			Join Capsulely Subscription!
		</div>
		<% end %>

		<div class="homeinfo2">
			Oh Yeah!</br>
				It’s only </br>
					<span class="bigfont">$24.</span>

		</div>

		<div class="homeinfo3">
			Only 480 Nickels.  How many
			couches would you have to
			dig thru?
		</div>

	</div>

	<div class="homeinfobox2">
		<div class="moreinfobox1">
			<h1>Launching June 2016</h1>

			<p>We will have only a limited number of subscriptions available.  Join now and get the plug hat and save your spot when we launch.  <%= link_to "View the plug hat.", pages_hats_path %></p>



		</div>

		<div class="moreinfobox2">
			<%= link_to pages_hats_path do %>
				<%= image_tag 'plughatimage2.png', :class => "fullimage2" %>
			<% end %>
		</div>

	</div>


</div>

app/views/pages/jackets.html.erb
<div class="postsection">
<% if @posts.any? %>

<ul>
	<%= render @posts %>
</ul>

<% end %>
</div>

app/views/pages/register.html.erb
<div class="registersection">
	<%= image_tag 'capsulely-brand-account.png', :class => "registerimage" %>

	<div class="registerheader">
		Partner with us.  We can help you increase your customer base and expand to new markets.
	</div>

	<%= link_to new_brand_path do %>
		<div class="registerbutton">Register Your Brand</div>
	<% end %>

	<ul class="registerpoints">
		<li><span class="headerpoint">Increase sales.</span></br>
			We handle marketing so you can focus on building a brand. 
		</li>
		<li><span class="headerpoint">Simple posting.</span></br>
			Just text or email us product info and we handle the rest. 
		</li>
		<li><span class="headerpoint">Easy process.</span></br>
			We handle customers and issues; you just handle shipments.
		</li>
		<li><span class="headerpoint">Join other great brands.</span></br>
			Your brand will be included in a diverse selection of brands.
		</li>
		<li><span class="headerpoint">Only a 25% commission.</span></br>
			Get more with us than selling wholesale.
		</li>		
		<li><span class="headerpoint">No upfront fees.</span></br>
			Never pay a monthly or upfront fee. Only pay for completed sales.
		</li>				
	</ul>

	<%= link_to new_brand_path do %>
		<div class="registerbutton">Join Today</div>
	<% end %>


</div>

app/views/pages/subscription.html.erb
<div class="postsection">

	<div class="howitworks">

		<h1>How It Works</h1>

		<div class="howitworksbox">
			<%= image_tag 'subscribe-howitworks-capsulely.png', :class => "fullimage" %>

			<p>Once you subscribe, you get 1 hat credit.  </br></br>You save mad dough each month by joining the squad.  </br></br>Use your credit each month to choose the hat you feeling and it will be sent to you right away.</p>
		</div>
		<div class="howitworksbox">
			
			<%= image_tag 'hat-package-howitworks-capsulely.png', :class => "fullimage" %>

			<p>We partner with cool designers and brands.  </br></br>Our designs are inspired by anything and everything in this wonderful world.  </br></br>Once you choose your design, choose type of hat you like.  Snapback, low profile hat, buckets and other hat options.</p>
		</div>

		<div class="howitworksbox">
			<%= image_tag 'hat-shipment-howitworks-capsulely.png', :class => "fullimage" %>

			<p>Your hat is carefully packed by supermodels with clean hands.  </br></br>You get first dips on exclusive and limited hats with a subscription.  </br></br>Join the squad and get hats sent to you each month.</p>
		</div>
	</div>

	<div class="packagecontent">

		<h1>Capsulely Subscription</h1>

		<h3>What to expect?</h3>
		<ul class="fa-ul includelist">
			<li><i class="fa-li fa fa-asterisk"></i>Each month you get 1 credit to select a hat you want delivered.</li>
			<li><i class="fa-li fa fa-asterisk"></i>Our designs are inspired by any and everything.</li>
			<li><i class="fa-li fa fa-asterisk"></i>Only a number of memberships are available.</li>
			<li><i class="fa-li fa fa-asterisk"></i>Top quaility hats and cool designs.</li>
			<li><i class="fa-li fa fa-asterisk"></i>Save money each month. Up to 30%.</li>
			<li><i class="fa-li fa fa-asterisk"></i>Exclusive offers and first access to limited designs.</li>
			<li><i class="fa-li fa fa-asterisk"></i>Easy cancellation.  Cancel anytime.</li>
			<li><i class="fa-li fa fa-asterisk"></i>You can expect inspirations from streetwear, pop culture, hiphop, sports, movies/tv, music, food, nature, technology and other cool things.</li>
		</ul>

	</div>
	<div class="subscribecontent">

		<%= image_tag 'plughatimage2.png', :class => "fullimage2" %>

		<%= link_to new_subscription_path, data: { no_turbolink: true } do %>
		<div class="subscribebox">
			BUY SUBSCRIPTION | $24
		</div>
		<% end %>

		<p>Get A New Hat Each Month.  Cancel anytime.</p>

	</div>

</div>

app/views/pages/tees.html.erb
<div class="postsection">
<% if @posts.any? %>

<ul>
	<%= render @posts %>
</ul>

<% end %>
</div>