config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe/webhooks'

  get 'pages/home'
  get 'pages/admin'
  get 'pages/tees'
  get 'pages/hats'
  get 'pages/jackets'
  get 'pages/accessories'
  get 'pages/subscription'
  get 'pages/about'
  get 'pages/register'

  get 'seller' => "posts#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'checking' => "brands#checking"
  get 'register' => "pages#register"
  get 'artists' => "brands#index"

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks =>"omniauth_callbacks"}


  #root "pages#home"
  #root 'pages#home'
  root 'exhibitions#index'

  resources :posts do
  	put :favorite, on: :member
  	put :like, on: :member

    resources :orders, only: [:new, :create] 

  end

  resources :profiles

  resource :subscription
  resource :card
  resources :addresses

  resources :credits 

  resources :brands


  resources :exhibitions do
      resources :posts
  
  end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :orders
	#is_impressionable :counter_cache => true, :column_name => :counter_cache, :unique => :request_hash
	has_many :brandizations
	has_many :brands, through: :brandizations

	validates :user_id, presence: true
	validates_presence_of :slug
	validates_presence_of :slug2

	has_attached_file :image, :styles => { :large => "1600x1200#", :medium => "800x600#", :thumb => "400x300#" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_attached_file :image2, :styles => { :large => "1600x1200#", :medium => "800x600#", :thumb => "400x300#" }
	validates_attachment_content_type :image2, :content_type => /\Aimage\/.*\Z/

	has_attached_file :image3, :styles => { :large => "1600x1200#", :medium => "800x600#", :thumb => "400x300#" }
	validates_attachment_content_type :image3, :content_type => /\Aimage\/.*\Z/

	# Favorited by users
	has_many :favorite_posts # just the 'relationships'
	has_many :favorited_by, through: :favorite_posts, source: :user

	# Liked by users
	has_many :like_posts # just the 'relationships'
	has_many :liked_by, through: :like_posts, source: :user

	scope :brand, -> brand { where("brand = ?", :brand) }

	scope :tee, ->{ where(:category => "Tee") }
	scope :hat, ->{ where(:category => "Hat") }
	scope :jacket, ->{ where(:category => "Jacket") }
	scope :accessory, ->{ where(:category => "Accessory") }

	def slug
	   	title.to_s.downcase.strip.gsub(" ", "-").gsub(/[^\w-]/, '') 
	end

	def slug2
		brand.to_s.downcase.strip.gsub(" ", "-").gsub(/[^\w-]/, '')
	end

	def to_param
    	"#{id}-#{slug2}-#{slug}"
  	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy, :favorite, :like]
	load_and_authorize_resource :only => [:show, :new, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	#impressionist :actions => [:show,:index], :unique => [:impressionable_type, :impressionable_id, :session_hash]
	has_scope :brand

	respond_to :html, :json, :js

	def seller
		@posts = Post.all.order("created_at DESC")
		
	end

	def index
		@brands = Brand.active
		
		@posts = apply_scopes(Post).hat.order("created_at DESC")
		#@posts = @posts.brand(params[:brand]) if params[:brand].present?

		if user_signed_in?
	      @favorites = current_user.favorites
	      @likes = current_user.likes
	    end
	end

	def show
		@brands = Brand.active

		if user_signed_in?
	      @favorites = current_user.favorites
	      @likes = current_user.likes
	    end

	    @randomposts = Post.where.not(id: @post).order("RANDOM()").take(6)
	end

	def new
		@brands = Brand.active
		@post = current_user.posts.build
	end

	def create
		@brands = Brand.active
		@post = current_user.posts.build(post_params)
		
		if @post.save
			redirect_to action: "index"
		else
			render 'new'
		end
	end

	def edit
		@brands = Brand.active
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end

	end

	def destroy
		@post.destroy
		redirect_to root_path, notice: "Successfully deleted post"
	end

	def favorite
    if user_signed_in?

      type = params[:type]
      if type == "favorite"
        current_user.favorites << @post

        respond_to do |format|
          format.html {redirect_to :back}
          format.json { render json: {  count: @post.favorited_by.count} }
          format.js { render :layout => false }
        end

      elsif type == "unfavorite"
        current_user.favorites.delete(@post)

        respond_to do |format|
          format.html {redirect_to :back}
          format.json { render json: {  count: @post.favorited_by.count } }
          format.js { render :layout => false }
        end

      else
        # Type missing, nothing happens
        redirect_to :back, notice: 'Nothing happened.'
      end

    else
        redirect_to new_user_registration_path
    end
  end

	def like
    if user_signed_in?

      type = params[:type]
      if type == "like"
        current_user.likes << @post

        respond_to do |format|
          format.html {redirect_to :back}
          format.json { render json: {  count: @post.liked_by.count} }
          format.js { render :layout => false }
        end

      elsif type == "unlike"
        current_user.likes.delete(@post)

        respond_to do |format|
          format.html {redirect_to :back}
          format.json { render json: {  count: @post.liked_by.count } }
          format.js { render :layout => false }
        end

      else
        # Type missing, nothing happens
        redirect_to :back, notice: 'Nothing happened.'
      end

    else
        redirect_to new_user_registration_path
    end
  end  

	private

	def post_params
		params.require(:post).permit(:brand, :title, :link, :price, :image, :image2, :image3, :category, :shipping_price, :quantity, :member_discount, :brand_id, brand_ids: [])
	end

	def set_post
		@post = Post.find(params[:id])
	end

	 def find_post
      user = User.find_by_username(params[:id])
    end
end

app/views/posts/_form.html.erb
  <div class="panel-heading">
    <h1>Add Post</h1>
  </div>

<div class="panel-body">
  <div class="panel panel-default">
    <%= form_for @post, html: { multipart: true } do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :image2 %>
        <%= f.file_field :image2, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :image3 %>
        <%= f.file_field :image3, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :brand %>
        <%= f.text_field :brand, class: "form-control" %>
        <%= f.hidden_field :slug2 %>
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
        <%= f.hidden_field :slug %>
        <%= f.label :price %>
        <%= f.text_field :price, class: "form-control" %>
        <%= f.label :member_discount %>
        <%= f.text_field :member_discount, class: "form-control" %>
        <%= f.label :shipping_price %>
        <%= f.text_field :shipping_price, class: "form-control" %>
        <%= f.label :quantity %>
        <%= f.text_field :quantity, class: "form-control" %>
        <%= f.label :link %>
        <%= f.text_field :link, class: "form-control" %>

          <% if can? :manage, :all %>

              <%= f.select :category, [ 'Tee', 'Hat', 'Jacket', 'Accessory' ], :prompt => 'Select One' %>

              <%= f.collection_select :brand_id, Brand.all, :id, :title, {} %>

              <% if false %><%= f.collection_select :brand_ids, Brand.all, :id, :title, {}, { :multiple => true} %><% end %>
          <% end %>

      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_randompost.html.erb
<li>
	<div class="postbox <%= post.id %> <%= post.category %>">
		<%= link_to post_path(post) do %>
		<div class="imagecircle <%= post.id %>">
		<div class="postinfo nodisplay <%= post.id %>">
			<h1><%= post.brand %></h1>
			<h2><%= post.title %></h2>


		</div>
			<%= image_tag post.image.url(:medium) %>




		</div>

		<% end %>



		<div class="postbuttons <%= post.id %>">

		<% if post.link.present? %>

		<%= link_to post.link, :target => "_blank" do %>
			<div class="allbutton linkbutton <%= post.id %>">
				<i class="fa fa-usd"></i>
				<p>BUY / <%= post.price %></p>

			</div>
		<% end %>

		<% else %>
			<div class="allbutton linkbutton <%= post.id %>">
				<i class="fa fa-usd"></i>
				<p>COMING SOON / <%= post.price %></p>

			</div>

		<% end %>

		<% if user_signed_in? %>
			<% if (@current_user.likes.include? post) %>
		
				<div class="allbutton likebutton <%= post.id %>">
					<i class="fa fa-heart"></i>
					<p>SHARE / <span class="likeup <%= post.id %>"><%= post.liked_by.count %></span></p>

				</div>

				<% else %>

				<%= link_to like_post_path(post, type: "like"), class: ['likeit', post.id], remote: true, data: { type: :json }, method: :put do %>
				<div class="allbutton likebutton <%= post.id %>">
					<i class="fa fa-heart"></i>
					<p>SHARE / <span class="likeup <%= post.id %>"><%= post.liked_by.count %></span></p>

				</div>
				<% end %>

				<div class="allbutton unlikebutton nodisplay <%= post.id %>">
					<i class="fa fa-heart"></i>
					<p>SHARE / <span class="likeup <%= post.id %>"><%= post.liked_by.count %></span></p>

				</div>
			<% end %>	
		<% else %>

			<div class="allbutton likebutton <%= post.id %>">
				<i class="fa fa-heart"></i>
				<p>SHARE / <span class="likeup <%= post.id %>"><%= post.liked_by.count %></span></p>

			</div>


					
		<% end %>

		<% if user_signed_in? %>
			<% if (@current_user.favorites.include? post) %>
				<%= link_to favorite_post_path(post, type: "unfavorite"), class: ['unfavit', post.id], remote: true, data: { type: :json }, method: :put do %>
					<div class="allbutton unsavebutton <%= post.id %>">
						<i class="fa fa-exclamation"></i>
						<p>UNSAVE / <span class="favup <%= post.id %>"><%= post.favorited_by.count %></span></p>

					</div>

				<% end %>	
				<%= link_to favorite_post_path(post, type: "favorite"), class: ['favit', post.id], remote: true, data: { type: :json }, method: :put do %>
				<div class="allbutton savebutton nodisplay <%= post.id %>">
					<i class="fa fa-exclamation"></i>
					<p>SAVE / <span class="favup <%= post.id %>"><%= post.favorited_by.count %></span></p>

				</div>
				<% end %>	


			<% else %>

				<%= link_to favorite_post_path(post, type: "favorite"), class: ['favit', post.id], remote: true, data: { type: :json }, method: :put do %>
				<div class="allbutton savebutton <%= post.id %>">
					<i class="fa fa-exclamation"></i>
					<p>SAVE / <span class="favup <%= post.id %>"><%= post.favorited_by.count %></span></p>

				</div>
				<% end %>	

				<%= link_to favorite_post_path(post, type: "unfavorite"), class: ['unfavit', post.id], remote: true, data: { type: :json }, method: :put do %>
					<div class="allbutton unsavebutton nodisplay <%= post.id %>">
						<i class="fa fa-exclamation"></i>
						<p>UNSAVE / <span class="favup <%= post.id %>"><%= post.favorited_by.count %></span></p>

					</div>

				<% end %>
			<% end %>

			<% else %>



			<div class="allbutton savebutton <%= post.id %>">
				<i class="fa fa-exclamation"></i>
				<p>SAVE / <span class="favup <%= post.id %>"><%= post.favorited_by.count %></span></p>

			</div>


					
		<% end %>
		</div>

	</div>
</li>

<script>

  $('.imagecircle' + '.<%= post.id %>').mouseover(function(){
    $('.postinfo' + '.<%= post.id %>').removeClass("nodisplay");
  });
  $('.imagecircle' + '.<%= post.id %>').mouseleave(function(){
    $('.postinfo' + '.<%= post.id %>').addClass("nodisplay");
  });
  $('.favit' + '.<%= post.id %>').on('ajax:success', function (e, data, status, xhr) { 
    console.log('byeyo');
    $('.favup' + '.<%= post.id %>').html(data.count);
    $('.unsavebutton' + '.<%= post.id %>').removeClass("nodisplay");
    $('.savebutton' + '.<%= post.id %>').addClass("nodisplay");
  });
  $('.unfavit' + '.<%= post.id %>').on('ajax:success', function (e, data, status, xhr) { 
    console.log('byeyo');
    $('.favup' + '.<%= post.id %>').html(data.count);
    $('.unsavebutton' + '.<%= post.id %>').addClass("nodisplay");
    $('.savebutton' + '.<%= post.id %>').removeClass("nodisplay");
  });
  $('.likeit' + '.<%= post.id %>').on('ajax:success', function (e, data, status, xhr) { 
    console.log('byeyo');
    $('.likeup' + '.<%= post.id %>').html(data.count);
    $('.unlikebutton' + '.<%= post.id %>').removeClass("nodisplay");
    $('.likebutton' + '.<%= post.id %>').addClass("nodisplay");
  });
</script>

app/views/posts/edit.html.erb
<div class="signup-back">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="postsection">
	<% if user_signed_in? %>
		<% if current_user.credits.where(creditactive: true).count > 1 %>
	<div class="creditalert">
		You have <%= current_user.credits.where(creditactive: true).count %> credits available to use.  Just hit "Use Credit" when placing order.
	</div>

	<% elsif current_user.credits.where(creditactive: true).count > 0 %>
	<div class="creditalert">
		You have <%= current_user.credits.where(creditactive: true).count %> credit available to use.  Just hit "Use Credit" when placing order.
	</div>
	<% end %>
	<% end %>

	<% if false %>
	<% if can? :manage, :all %>
    <div class="dropdown">
      <button class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        Brands
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

         <% @brands.each do |brand| %>
              <li role="presentation"><%= link_to brand.title, posts_path(:brand => brand) %></li>
            <% end %>
      </ul>
    </div>
    <% end %>
    <% end %>
	
<% if @posts.any? %>

<ul>
	<%= render @posts %>
</ul>

<% end %>
</div>

app/views/posts/new.html.erb
<div class="signup-back">

	<%= render 'form' %>

</div>


app/views/posts/seller.html.erb
<table class="table table-striped table-bordered">
	<tr>
		<th class="center">Image</th>
		<th class="center">Brand</th>
		<th class="center">Title</th>
		<th class="center">Price</th>
		<th class="center">Link</th>
	</tr>

	<% @posts.each do |post| %>
		<tr>
			<td><%= image_tag post.image.url(:thumb) %></td>
			<td><%= post.brand %></td>
			<td><%= post.title %></td>
			<td><% if post.price.present? %><%= number_to_currency(post.price) %><% end %></td>
			<td><% if post.link.present? %><%= post.link %><% end %></td>
			<td>
				<div class="btn-group">
					<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
						Action <span class="caret"></div>
					</button>
					<ul class="dropdown-menu">
						<li><%= link_to "View", post, class: "btn btn-link" %></li>
						<li><%= link_to "Edit", edit_post_path(post), class: "btn btn-link" %></li>
						<li><%= link_to "Destroy", post, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-link" %></li>
					</ul>
				</div>
			</td>
		</tr>
	<% end %>
</table>

<br>

<% if user_signed_in? %>
	<%= link_to 'New Post', new_post_path, class: "btn btn-link" %>
<% end %>
