config/routes.rb
Rails.application.routes.draw do

  mount StripeEvent::Engine, at: '/stripe/webhooks'

  get 'pages/home'
  get 'pages/admin'
  get 'pages/tees'
  get 'pages/hats'
  get 'pages/jackets'
  get 'pages/accessories'
  get 'pages/subscription'
  get 'pages/about'
  get 'pages/register'

  get 'seller' => "posts#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'checking' => "brands#checking"
  get 'register' => "pages#register"
  get 'artists' => "brands#index"

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks =>"omniauth_callbacks"}


  #root "pages#home"
  #root 'pages#home'
  root 'exhibitions#index'

  resources :posts do
  	put :favorite, on: :member
  	put :like, on: :member

    resources :orders, only: [:new, :create] 

  end

  resources :profiles

  resource :subscription
  resource :card
  resources :addresses

  resources :credits 

  resources :brands


  resources :exhibitions do
      resources :posts
  
  end

  

end

app/views/layouts/_header.html.erb
<div class="header-section">
	<% if false %>
	<div class="header-signup <%= subscription_header_class %>">
		<div id="sitemenu-icon" class="open active">
			<span class="line1"></span>
			<span class="line3"></span>
		</div>

		<%= image_tag 'zoe-logo-white.png', :class => "headerimage2" %>	
		<h2>Get Capsulely Monthly Hats</h2>
		<p>Get exclusive releases and member discounts.</p>
		<%= link_to pages_subscription_path do %>
			<div class="signupbutton">Hook Me Up</div>
		<% end %>
		<div class="nothanks">I'm Good</div>

	</div>
	<% end %>

	<div class="header-signup <%= subscription_header_class %>">
		<div id="sitemenu-icon" class="open active">
			<span class="line1"></span>
			<span class="line3"></span>
		</div>

		<%= image_tag 'zoe-logo-white.png', :class => "headerimage2" %>	
		<p>Get exclusive releases and member discounts.</p>
		<%= link_to new_user_registration_path do %>
			<div class="signupbutton">Join The Art Club</div>
		<% end %>
		<div class="nothanks">I'm Good</div>

	</div>

	<ul class="header-ul">
		<%= link_to root_path do %>
			<li class="nav0"><%= image_tag 'zoe-logo.png', :class => "headerimage" %></li>
		<% end %>
		<%= link_to posts_path do %>
		<li class="nav1">Original Art</li>
		<% end %>

		<% if @brands.any? %>
		<li class="nav2">
	    <div class="dropdown">
	      <span class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
	        Artists
	        <span class="caret"></span>
	      </span>
	      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

	         <% @brands.each do |brand| %>
	              <li role="presentation"><%= link_to brand.title, brand_url(:id => brand.brandname) %></li>
	            <% end %>
	      </ul>
	    </div>
		</li>
		<% end %>
		
		<% if false %>
		<%= link_to pages_subscription_path do %>
		<li class="nav2">How It Works</li>
		<% end %>
		<% end %>

		<%= link_to pages_about_path do %>
		<li class="nav3">About</li>
		<% end %>

		<% if false %>
		<% if user_signed_in? %>
		<% if current_user.stripe_id.present? %>
			<li class="nav4">	
				Credits: <%= current_user.credits.where(creditactive: true).count %>
			</li>
		<% end %>
		<% end %>
		<% end %>


		<li class="nav5"><div id="openbutton" class="rec-overall"><div class="large-rec"></div><div class="small-rec"></div></div></li>
	</ul>

</div>

<div class="overlay nodisplay"></div>

	<div class="rightmenu">
	  <ul>
	  	<% if user_signed_in? %>
	  	<li>
		    
		    <%= link_to profile_url(:id => current_user.username) do %>
		    	<span class="menu-li">Gallery</span>
		    <% end %>
		    
		</li>
		<% end %>

		<% if false %>
		<li>
			<% if current_user_subscribed? %>


				
			<% else %>
			<%= link_to "Subscribe To Capsulely", new_subscription_path, data: { no_turbolink: true } %>

			<% end %>

		</li>
		<% end %>
		
		<li>
			<% if false %>
			<% if user_signed_in? %>
			<% if current_user.stripe_id.present? %>

			Credits: <%= current_user.credits.where(creditactive: true).count %>

			<% end %>
			<% end %>
			<% end %>
		</li>
	  </ul>

	  <ul>
	
	  	<%= link_to posts_path do %>
	  	<li>
			Original Art
		</li>
		<% end %>

		<% if false %>
		<%= link_to pages_subscription_path do %>
	  	<li>
			How It Works
		</li>
		<% end %>
		<% end %>

		<%= link_to pages_about_path do %>
	  	<li>
			About
		</li>
		<% end %>

	  </ul>

	  <ul>
	  	<% if user_signed_in? %>
	    <li>
	      <%= link_to edit_user_registration_path do %>
	      <span class="menu-li">Account</span>
	      <% end %>

	    </li>
	    <% if can? :manage, :all %>
	    <li>
	      <%= link_to sales_path do %>
	      <span class="menu-li">Sales History</span>
	      <% end %>

	    </li>
	    <li>
	      <%= link_to purchases_path do %>
	      <span class="menu-li">Purchase History</span>
	      <% end %>

	    </li>
	    <% end %>


	    <% else %>
	    <li>
	      <%= link_to new_user_registration_path do %>
	      <span class="menu-li">Sign Up / Sign In</span>
	      <% end %>
	    </li>
	    <% end %>

	    <% if user_signed_in? %>
	    <li>
	      <%= link_to destroy_user_session_path, :method => :delete do %>
	      <span class="menu-li">Sign out</span>
	      <% end %>
	    </li>
	    <% end %>
	  </ul>

	</div>

<script>
	$('#openbutton').click(function(){
		$('.rightmenu').addClass('revealed');
		$('.overlay').removeClass('nodisplay');
		$('body').addClass("noscroll");
	});
	$('.overlay').click(function(){
		$('.rightmenu').removeClass('revealed');
		$('.overlay').addClass('nodisplay');
		$('body').removeClass("noscroll");
		$('.signup-popup').addClass("nodisplay");
		$('.social-popup').addClass("nodisplay");
	});
	$("#sitemenu-icon").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});
	$(".nothanks").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});
 	$('#teebutton').click(function(){
		$('.Tee').removeClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#hatbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').removeClass('nodisplay');
	});
 	$('#jacketbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').removeClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#accessorybutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').removeClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
</script>

app/views/layouts/_header2.html.erb
<div class="header-section">
	<% if false %>
	<div class="header-signup <%= subscription_header_class %>">
		<div id="sitemenu-icon" class="open active">
			<span class="line1"></span>
			<span class="line3"></span>
		</div>

		<%= image_tag 'zoe-logo-white.png', :class => "headerimage2" %>
		<h2>Get Capsulely Monthly Hats</h2>
		<p>Get exclusive releases and member discounts.</p>
		<%= link_to pages_subscription_path do %>
			<div class="signupbutton">Hook Me Up</div>
		<% end %>
		<div class="nothanks">I'm Good</div>

	</div>
	<% end %>

	<div class="header-signup <%= subscription_header_class %>">
		<div id="sitemenu-icon" class="open active">
			<span class="line1"></span>
			<span class="line3"></span>
		</div>

		<%= image_tag 'zoe-logo-white.png', :class => "headerimage2" %>
		<p>Get exclusive releases and member discounts.</p>
		<%= link_to new_user_registration_path do %>
			<div class="signupbutton">Join The Art Club</div>
		<% end %>
		<div class="nothanks">I'm Good</div>

	</div>

	<ul class="header-ul">
		<%= link_to root_path do %>
		<li class="nav0"><%= image_tag 'zoe-logo.png', :class => "headerimage" %></li><% end %>
		<%= link_to posts_path do %>
		<li class="nav1">Original Art</li>
		<% end %>
		
		<% if false %>
		<%= link_to pages_subscription_path do %>
		<li class="nav2">How It Works</li>
		<% end %>
		<% end %>

		<%= link_to pages_about_path do %>
		<li class="nav3">About</li>
		<% end %>

		<% if false %>
		<% if user_signed_in? %>
		<% if current_user.stripe_id.present? %>
			<li class="nav4">	
				Credits: <%= current_user.credits.where(creditactive: true).count %>
			</li>
		<% end %>
		<% end %>
		<% end %>


		<li class="nav5"><div id="openbutton" class="rec-overall"><div class="large-rec"></div><div class="small-rec"></div></div></li>
	</ul>

</div>

<div class="overlay nodisplay"></div>

	<div class="rightmenu">
	  <ul>
	  	<% if user_signed_in? %>
	  	<li>
		    
		    <%= link_to profile_url(:id => current_user.username) do %>
		    	<span class="menu-li">Gallery</span>
		    <% end %>
		    
		</li>
		<% end %>

		<% if false %>
		<li>
			<% if current_user_subscribed? %>


				
			<% else %>
			<%= link_to "Subscribe To Capsulely", new_subscription_path, data: { no_turbolink: true } %>

			<% end %>

		</li>
		<% end %>
		
		<li>
			<% if false %>
			<% if user_signed_in? %>
			<% if current_user.stripe_id.present? %>

			Credits: <%= current_user.credits.where(creditactive: true).count %>

			<% end %>
			<% end %>
			<% end %>
		</li>
	  </ul>

	  <ul>
	  	<%= link_to posts_path do %>
	  	<li>
			Original Art
		</li>
		<% end %>

		<% if false %>
		<%= link_to pages_subscription_path do %>
	  	<li>
			How It Works
		</li>
		<% end %>
		<% end %>

		<%= link_to pages_about_path do %>
	  	<li>
			About
		</li>
		<% end %>

	  </ul>

	  <ul>
	  	<% if user_signed_in? %>
	    <li>
	      <%= link_to edit_user_registration_path do %>
	      <span class="menu-li">Account</span>
	      <% end %>

	    </li>
	    <% if can? :manage, :all %>
	    <li>
	      <%= link_to sales_path do %>
	      <span class="menu-li">Sales History</span>
	      <% end %>

	    </li>
	    <li>
	      <%= link_to purchases_path do %>
	      <span class="menu-li">Purchase History</span>
	      <% end %>

	    </li>
	    <% end %>


	    <% else %>
	    <li>
	      <%= link_to new_user_registration_path do %>
	      <span class="menu-li">Sign Up / Sign In</span>
	      <% end %>
	    </li>
	    <% end %>

	    <% if user_signed_in? %>
	    <li>
	      <%= link_to destroy_user_session_path, :method => :delete do %>
	      <span class="menu-li">Sign out</span>
	      <% end %>
	    </li>
	    <% end %>
	  </ul>

	</div>

<script>
	$('#openbutton').click(function(){
		$('.rightmenu').addClass('revealed');
		$('.overlay').removeClass('nodisplay');
		$('body').addClass("noscroll");
	});
	$('.overlay').click(function(){
		$('.rightmenu').removeClass('revealed');
		$('.overlay').addClass('nodisplay');
		$('body').removeClass("noscroll");
		$('.signup-popup').addClass("nodisplay");
		$('.social-popup').addClass("nodisplay");
	});
	$("#sitemenu-icon").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});
	$(".nothanks").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});
 	$('#teebutton').click(function(){
		$('.Tee').removeClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#hatbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').removeClass('nodisplay');
	});
 	$('#jacketbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').removeClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#accessorybutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').removeClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
</script>

app/views/layouts/_header3.html.erb
<div class="header-section">

	<ul class="header-ul">
		<%= link_to root_path do %>
		<li class="nav0"><%= image_tag 'zoe-logo2.png', :class => "headerimage" %></li><% end %>
		<%= link_to posts_path do %>
		<li class="nav1">Original Art</li>
		<% end %>

		<% if @brands.any? %>
		<li class="nav2">
	    <div class="dropdown">
	      <span class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
	        Artists
	        <span class="caret"></span>
	      </span>
	      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

	         <% @brands.each do |brand| %>
	              <li role="presentation"><%= link_to brand.title, brand_url(:id => brand.brandname) %></li>
	            <% end %>
	      </ul>
	    </div>
		</li>
		<% end %>
		
		<% if false %>
		<%= link_to pages_subscription_path do %>
		<li class="nav2">How It Works</li>
		<% end %>
		<% end %>

		<%= link_to pages_about_path do %>
		<li class="nav3">About</li>
		<% end %>

		<% if false %>
		<% if user_signed_in? %>
		<% if current_user.stripe_id.present? %>
			<li class="nav4">	
				Credits: <%= current_user.credits.where(creditactive: true).count %>
			</li>
		<% end %>
		<% end %>
		<% end %>


		<li class="nav5"><div id="openbutton" class="rec-overall"><div class="large-rec"></div><div class="small-rec"></div></div></li>
	</ul>

</div>

<div class="overlay nodisplay"></div>

	<div class="rightmenu">
	  <ul>
	  	<% if user_signed_in? %>
	  	<li>
		    
		    <%= link_to profile_url(:id => current_user.username) do %>
		    	<span class="menu-li">Gallery</span>
		    <% end %>
		    
		</li>
		<% end %>

		<% if false %>
		<li>
			<% if current_user_subscribed? %>


				
			<% else %>
			<%= link_to "Subscribe To Capsulely", new_subscription_path, data: { no_turbolink: true } %>

			<% end %>

		</li>
		<% end %>
		
		<li>
			<% if false %>
			<% if user_signed_in? %>
			<% if current_user.stripe_id.present? %>

			Credits: <%= current_user.credits.where(creditactive: true).count %>

			<% end %>
			<% end %>
			<% end %>
		</li>
	  </ul>

	  <ul>
	
	  	<%= link_to posts_path do %>
	  	<li>
			Original Art
		</li>
		<% end %>

		<% if false %>
		<%= link_to pages_subscription_path do %>
	  	<li>
			How It Works
		</li>
		<% end %>
		<% end %>

		<%= link_to pages_about_path do %>
	  	<li>
			About
		</li>
		<% end %>

	  </ul>

	  <ul>
	  	<% if user_signed_in? %>
	    <li>
	      <%= link_to edit_user_registration_path do %>
	      <span class="menu-li">Account</span>
	      <% end %>

	    </li>
	    <% if can? :manage, :all %>
	    <li>
	      <%= link_to sales_path do %>
	      <span class="menu-li">Sales History</span>
	      <% end %>

	    </li>
	    <li>
	      <%= link_to purchases_path do %>
	      <span class="menu-li">Purchase History</span>
	      <% end %>

	    </li>
	    <% end %>


	    <% else %>
	    <li>
	      <%= link_to new_user_registration_path do %>
	      <span class="menu-li">Sign Up / Sign In</span>
	      <% end %>
	    </li>
	    <% end %>

	    <% if user_signed_in? %>
	    <li>
	      <%= link_to destroy_user_session_path, :method => :delete do %>
	      <span class="menu-li">Sign out</span>
	      <% end %>
	    </li>
	    <% end %>
	  </ul>

	</div>

<script>
	$('#openbutton').click(function(){
		$('.rightmenu').addClass('revealed');
		$('.overlay').removeClass('nodisplay');
		$('body').addClass("noscroll");
	});
	$('.overlay').click(function(){
		$('.rightmenu').removeClass('revealed');
		$('.overlay').addClass('nodisplay');
		$('body').removeClass("noscroll");
		$('.signup-popup').addClass("nodisplay");
		$('.social-popup').addClass("nodisplay");
	});
	$("#sitemenu-icon").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});
	$(".nothanks").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});
 	$('#teebutton').click(function(){
		$('.Tee').removeClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#hatbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').removeClass('nodisplay');
	});
 	$('#jacketbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').removeClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#accessorybutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').removeClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
</script>

app/views/layouts/_homeheader.html.erb
<div class="header-section">

	<div class="header-signup">
		<div id="sitemenu-icon" class="open active">
	<span class="line1"></span>
	<span class="line3"></span>
</div>

		<%= image_tag 'capsulely-logo.png', :class => "headerimage2" %>	
		<h2>Get Capsulely Monthly Packages</h2>
		<p>Limited Supply Available</p>
		<div class="signupbutton">Hook Me Up</div>
		<div class="nothanks">I'm Good</div>

	</div>


	<ul class="header-ul">
		<%= link_to root_path do %>
		<li class="nav0"><%= image_tag 'capsulely-logo3.png', :class => "headerimage" %></li><% end %>
		<%= link_to pages_tees_path do %>
		<li class="nav1" id="teebutton">Tees</li>
		<% end %>
		<%= link_to pages_hats_path do %>
		<li class="nav2" id="hatbutton">Hats</li>
		<% end %>
		<%= link_to pages_jackets_path do %>
		<li class="nav3" id="jacketbutton">Jackets</li>
		<% end %>
		<%= link_to pages_accessories_path do %>
		<li class="nav4" id="accessorybutton">Accessories</li>
		<% end %>
		<li class="nav5"><div id="openbutton" class="rec-overall"><div class="large-rec"></div><div class="small-rec"></div></div></li>
	</ul>

</div>

<div class="overlay nodisplay"></div>

	<div class="rightmenu">
	  <ul>
	  	<% if user_signed_in? %>
	  	<li>
		    
		    <%= link_to profile_url(:id => current_user.username) do %>
		    	<span class="menu-li">Digital Capsule</span>
		    <% end %>
		    
		</li>
		<% end %>
	  </ul>

	  <ul>
	  	<%= link_to pages_tees_path do %>
	  	<li>
			Tees
		</li>
		<% end %>
		<%= link_to pages_hats_path do %>
	  	<li>
			Hats
		</li>
		<% end %>
		<%= link_to pages_jackets_path do %>
	  	<li>
			Jackets
		</li>
		<% end %>
		<%= link_to pages_accessories_path do %>
	  	<li>
			Accesories
		</li>
		<% end %>
	  </ul>

	  <ul>
	  	<% if user_signed_in? %>
	    <li>
	      <%= link_to edit_user_registration_path do %>
	      <span class="menu-li">Account</span>
	      <% end %>

	    </li>
	    <% else %>
	    <li>
	      <%= link_to new_user_session_path do %>
	      <span class="menu-li">Sign Up / Sign In</span>
	      <% end %>
	    </li>
	    <% end %>

	    <% if user_signed_in? %>
	    <li>
	      <%= link_to destroy_user_session_path, :method => :delete do %>
	      <span class="menu-li">Sign out</span>
	      <% end %>
	    </li>
	    <% end %>
	  </ul>
		<div class="ccevanslogo">
			<%= link_to 'http://ccevans.com', :target => '_blank' do %>
			<%= image_tag 'itsaspaceship.png', :class => "headerimage" %>
			<% end %>
		</div>
	</div>

<script>
	$('#openbutton').click(function(){
		$('.rightmenu').addClass('revealed');
		$('.overlay').removeClass('nodisplay');
		$('body').addClass("noscroll");
	});
	$('.overlay').click(function(){
		$('.rightmenu').removeClass('revealed');
		$('.overlay').addClass('nodisplay');
		$('body').removeClass("noscroll");
		$('.signup-popup').addClass("nodisplay");
		$('.social-popup').addClass("nodisplay");
	});
	$("#sitemenu-icon").click(function(){
		$(".header-signup").addClass("nodisplay");
		$("#sitemenu-icon").removeClass("open");
		$("#sitemenu-icon").removeClass("active");
		$('body').removeClass("noscroll");
	});

 	$('#teebutton').click(function(){
		$('.Tee').removeClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#hatbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').removeClass('nodisplay');
	});
 	$('#jacketbutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').removeClass('nodisplay');
		$('.Accessory').addClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
 	$('#accessorybutton').click(function(){
		$('.Tee').addClass('nodisplay');
		$('.Jacket').addClass('nodisplay');
		$('.Accessory').removeClass('nodisplay');
		$('.Hat').addClass('nodisplay');
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zoe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'https://js.stripe.com/v2/', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" media="all" rel="stylesheet" type="text/css" />
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



  <meta name="viewport" content="width=device-width" />



  <script src="https://use.typekit.net/mfr0vxt.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70989632-5', 'auto');
  ga('send', 'pageview');

</script>
  
</head>
<body>
	    
    <% if current_page?(register_path) %>
      <%= render 'layouts/header3' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>


	<div class="notice flash-message"> <span style="background-color: #f1c40f"><%= notice %></span> </div>
<div class="alert flash-message"> <span style="background-color: #c0392b"><%= alert %></span> </div> 

<%= yield %>

</body>
</html>

<script>
  $(function() {
     $('.flash-message').delay(500).fadeIn('normal', function() {
        $(this).delay(2500).fadeOut();
     });
  });
  </script>